# -*- coding: utf-8 -*-
"""Weather_Forecasting_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IBPSARZbRqoZG7Nga_QwIIdXfpOZvOOT

## Problem-04 : Make a model for Forecast Weather Using ARIMA
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app.py
# 
# import streamlit as st
# import pandas as pd
# import pickle
# 
# # Initialize feature_names to prevent NameError if model loading fails
# feature_names = []
# 
# # Load the trained model and feature names from the pickle file
# try:
#     with open("rainfall_prediction_model.pkl", "rb") as file:
#         model_data = pickle.load(file)
#     model = model_data["model"]
#     feature_names = model_data["feature_names"]
# except FileNotFoundError:
#     st.error("Model file 'rainfall_prediction_model.pkl' not found. Please ensure the model is saved correctly.")
#     st.stop()
# except Exception as e:
#     st.error(f"Error loading model: {e}")
#     st.stop()
# 
# # Streamlit App Title
# st.title("Rainfall Prediction App")
# st.write("Enter the weather parameters to predict if there will be rainfall.")
# 
# # Input fields for user data
# st.header("Input Weather Parameters")
# 
# # Create input widgets for each feature dynamically
# input_values = {}
# for feature in feature_names:
#     if feature == 'pressure':
#         input_values[feature] = st.number_input(f"Enter {feature.replace('_', ' ').title()} (hPa)", value=1015.9, format="%.1f")
#     elif feature == 'dewpoint':
#         input_values[feature] = st.number_input(f"Enter {feature.replace('_', ' ').title()} (°C)", value=19.9, format="%.1f")
#     elif feature == 'humidity':
#         input_values[feature] = st.number_input(f"Enter {feature.replace('_', ' ').title()} (%)", value=95, min_value=0, max_value=100)
#     elif feature == 'cloud':
#         input_values[feature] = st.number_input(f"Enter {feature.replace('_', ' ').title()} (% coverage)", value=81, min_value=0, max_value=100)
#     elif feature == 'sunshine':
#         input_values[feature] = st.number_input(f"Enter {feature.replace('_', ' ').title()} (hours)", value=0.0, format="%.1f")
#     elif feature == 'winddirection':
#         input_values[feature] = st.number_input(f"Enter {feature.replace('_', ' ').title()} (degrees)", value=40.0, format="%.1f")
#     elif feature == 'windspeed':
#         input_values[feature] = st.number_input(f"Enter {feature.replace('_', ' ').title()} (km/h)", value=13.7, format="%.1f")
#     else:
#         input_values[feature] = st.number_input(f"Enter {feature.replace('_', ' ').title()}", value=0.0, format="%.1f")
# 
# 
# # Create a DataFrame from the input values
# input_df = pd.DataFrame([input_values], columns=feature_names)
# 
# st.subheader("Provided Input Data:")
# st.dataframe(input_df)
# 
# # Make prediction button
# if st.button("Predict Rainfall"):
#     prediction = model.predict(input_df)
# 
#     st.subheader("Prediction Result:")
#     if prediction[0] == 1:
#         st.success("Prediction: It is likely to rain!")
#         st.image("https://media.giphy.com/media/l4FGkjPjYF59W8rWw/giphy.gif", caption="Rainfall Expected")
#     else:
#         st.info("Prediction: No rainfall expected.")
#         st.image("https://media.giphy.com/media/26FPC3r3wGv90XhMA/giphy.gif", caption="No Rainfall")

!streamlit run streamlit_app.py &>/dev/null& # This command starts the Streamlit app in the background.

import time
time.sleep(5) # Give the app a moment to start

# You can access the app via ngrok or localtunnel.
# For ngrok:
# !pip install pyngrok
# from pyngrok import ngrok
# print(ngrok.connect(8501))

# For localtunnel (often easier for Colab):
!npm install -g localtunnel
!lt --port 8501

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.utils import resample
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import pickle

"""**Data Collection and Processing**"""

from google.colab import files
uploaded = files.upload()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.utils import resample
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import pickle

!pip install streamlit

import io
data = pd.read_csv(io.BytesIO(uploaded['Rainfall.csv']))
print(type(data))

data.shape

data_shape = data.shape
html_output = f"<table><tr><th>Rows</th><th>Columns</th></tr><tr><td>{data_shape[0]}</td><td>{data_shape[1]}</td></tr></table>"
display(html_output)

data.head()

data.tail()

data["day"].unique()

print("Data Info:")
data.info()

data.columns

# remove extra  spaces in all columns
data.columns = data.columns.str.strip()

data.columns

print("Data Info:")
data.info()

data = data.drop(columns=["day"], errors='ignore')

data.head()

# checking the number of missing values
print(data.isnull().sum())

data["winddirection"].unique()

# handle missing values
data["winddirection"] = data["winddirection"].fillna(data["winddirection"].mode()[0])
data["windspeed"] = data["windspeed"].fillna(data["windspeed"].median())

# checking the number of missing values
print(data.isnull().sum())

data["rainfall"].unique()

# converting the yes & no to 1 and 0 respectively
data["rainfall"] = data["rainfall"].map({"yes": 1, "no": 0})

data.head()

"""**Exploratory Data Analysis (EDA)**"""

data.shape

# setting plot style for all the plots
sns.set(style="whitegrid")

data.describe()

data.columns

plt.figure(figsize=(15, 10))

for i, column in enumerate(['pressure', 'maxtemp', 'temparature', 'mintemp', 'dewpoint', 'humidity','cloud', 'sunshine', 'windspeed'], 1):
  plt.subplot(3, 3, i)
  sns.histplot(data[column], kde=True)
  plt.title(f"Distribution of {column}")

plt.tight_layout()
plt.show()

plt.figure(figsize=(6, 4))
sns.countplot(x="rainfall", data=data)
plt.title("Distribution of Rainfall")
plt.show()

# correlation matrix
plt.figure(figsize=(10, 8))
sns.heatmap(data.corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation heatmap")
plt.show()

plt.figure(figsize=(15, 10))

for i, column in enumerate(['pressure', 'maxtemp', 'temparature', 'mintemp', 'dewpoint', 'humidity','cloud', 'sunshine', 'windspeed'], 1):
  plt.subplot(3, 3, i)
  sns.boxplot(data[column])
  plt.title(f"Boxplot of {column}")

plt.tight_layout()
plt.show()

"""**Data Preprocessing**"""

# drop highly correlated column
data = data.drop(columns=['maxtemp', 'temparature', 'mintemp'])

data.head()

print(data["rainfall"].value_counts())

# separate majority and minority class
df_majority = data[data["rainfall"] == 1]
df_minority = data[data["rainfall"] == 0]

print(df_majority.shape)
print(df_minority.shape)

# downsample majority class to match minority count
df_majority_downsampled = resample(df_majority, replace=False, n_samples=len(df_minority), random_state=42)

df_majority_downsampled.shape

df_downsampled = pd.concat([df_majority_downsampled, df_minority])

df_downsampled.shape

df_downsampled.head()

# shuffle the final dataframe
df_downsampled = df_downsampled.sample(frac=1, random_state=42).reset_index(drop=True)

df_downsampled.head()

df_downsampled["rainfall"].value_counts()

# split features and target as X and y
X = df_downsampled.drop(columns=["rainfall"])
y = df_downsampled["rainfall"]

print(X)

print(y)

# splitting the data into training data and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""**Model Training**"""

rf_model = RandomForestClassifier(random_state=42)

param_grid_rf = {
    "n_estimators": [50, 100, 200],
    "max_features": ["sqrt", "log2"],
    "max_depth": [None, 10, 20, 30],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4]
}

# Hypertuning using GridSearchCV
grid_search_rf = GridSearchCV(estimator=rf_model, param_grid=param_grid_rf, cv=5, n_jobs=-1, verbose=2)

grid_search_rf.fit(X_train, y_train)

best_rf_model = grid_search_rf.best_estimator_

print("best parameters for Random Forest:", grid_search_rf.best_params_)

"""**Model Evaluation**"""

cv_scores = cross_val_score(best_rf_model, X_train, y_train, cv=5)
print("Cross-validation scores:", cv_scores)
print("Mean cross-validation score:", np.mean(cv_scores))

# test set performance
y_pred = best_rf_model.predict(X_test)

print("Test set Accuracy:", accuracy_score(y_test, y_pred))
print("Test set Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

"""**Prediction on unknown data**"""

input_data = (1015.9, 19.9, 95, 81, 0.0, 40.0, 13.7)

input_df = pd.DataFrame([input_data], columns=['pressure', 'dewpoint', 'humidity', 'cloud', 'sunshine','winddirection', 'windspeed'])

input_df

prediction = best_rf_model.predict(input_df)

print(prediction)

prediction[0]

prediction = best_rf_model.predict(input_df)
print("Prediction result:", "Rainfall" if prediction[0] == 1 else "No Rainfall")

# save model and feature names to a pickle file
model_data = {"model": best_rf_model, "feature_names": X.columns.tolist()}

with open("rainfall_prediction_model.pkl", "wb") as file:
  pickle.dump(model_data, file)

"""**Load the saved model and file and use it for prediction**"""

import pickle
import pandas as pd

# load the trained model and feature names from the pickle file
with open("rainfall_prediction_model.pkl", "rb") as file:
  model_data = pickle.load(file)

model = model_data["model"]
feature_names = model_data["feature_names"]

input_data = (1015.9, 19.9, 95, 81, 0.0, 40.0, 13.7)

input_df = pd.DataFrame([input_data], columns=feature_names)

prediction = best_rf_model.predict(input_df)
print("Prediction result:", "Rainfall" if prediction[0] == 1 else "No Rainfall")